# Generated by Django 2.2.12 on 2020-08-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_subscriptions', '0002_auto_20200801_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=32)),
                ('staff_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_subscriptions.StaffEmployeeSubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=32)),
                ('staff_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_subscriptions.StaffEmployeeSubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
