# Generated by Django 2.2.12 on 2020-08-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='staff_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_subscription_payment', to='staff_subscriptions.StaffEmployeeSubscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=32, null=True),
        ),
    ]
