# Generated by Django 2.2.12 on 2020-07-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('staff_union', models.CharField(blank=True, max_length=256, null=True)),
                ('nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('TRANSFERED', 'TRANSFERED')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffEmployeeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=128)),
                ('subscription_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('staff_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_subscriptions.StaffEmployee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
