# Generated by Django 2.2.12 on 2020-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffemployee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('TRANSFERED', 'TRANSFERED'), ('REMOVED', 'REMOVED')], max_length=32),
        ),
    ]
