# Generated by Django 2.2.12 on 2020-08-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_subscriptions', '0002_auto_20200801_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffemployeesubscription',
            name='subscription_payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=32),
        ),
    ]
