# Generated by Django 2.2.12 on 2020-08-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_subscriptions', '0003_staffemployeesubscription_subscription_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
